AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Password Caddy Api
  
  AWS SAM Template for creating the API resources (API Gateway & Lambda Functions)
  for the Password Caddy Api

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment of the Stack. Either dev or prod

Globals:
  Function:
    Timeout: 30

Resources:
  PasswordCaddyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: "HTTP API for Password Caddy Applications"
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "password-caddy-api-${Env}-CreateUser"
      CodeUri: src/controllers/create-user/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/user
            Method: POST
            ApiId: !Ref PasswordCaddyApi
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "password-caddy-api-${Env}-Login"
      CodeUri: src/controllers/login/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/login
            Method: GET
            ApiId: !Ref PasswordCaddyApi

Outputs:
  # Api
  PasswordCaddyApi:
    Description: "HTTP API Gateway URL for Password Caddy Api"
    Value: !Sub "https://${PasswordCaddyApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub "PasswordCaddyApi-${Env}"
  
  # Endpoints
  LoginEndpoint:
    Description: "Endpoint for Login Lambda"
    Value: !Sub "https://${PasswordCaddyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/login"
  CreateUserEndpoint:
    Description: "Endpoint for Login Lambda"
    Value: !Sub "https://${PasswordCaddyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/user"
  
  # Lambda Functions
  LoginFunctionArn:
    Description: "Create User Function Arn"
    Value: !GetAtt LoginFunction.Arn
  CreateUserFunctionArn:
    Description: "Create User Function Arn"
    Value: !GetAtt CreateUserFunction.Arn
  
  # IAM
  CreateUserFunctionIamRole:
    Description: "IAM Role for Password Caddy API Login Function"
    Value: !GetAtt LoginFunctionRole.Arn
  CreateUserFunctionIamRole:
    Description: "IAM Role for Password Caddy API Create User Function"
    Value: !GetAtt CreateUserFunctionRole.Arn
