AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM Template for creating the API resources (API Gateway & Lambda Functions)
  for the Password Caddy Api

Parameters:
  ENV:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment of the Stack. Either dev or prod
  ACCOUNTID:
    Type: String
    Default: ""
    Description: AWS Account ID
  

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        TEST_TOKEN:
        EXPIRATION:

Resources:
  PasswordCaddyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: "HTTP API for Password Caddy Applications"
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "password-caddy-api-${ENV}-v1-CreateUser"
      Role: !Sub "arn:aws:iam::${ACCOUNTID}:role/password-caddy/lambda/${ENV}/dynamodb"
      CodeUri: src/controllers/create-user/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/user
            Method: POST
            ApiId: !Ref PasswordCaddyApi
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "password-caddy-api-${ENV}-v1-Login"
      # Role: !Sub "arn:aws:iam::${ACCOUNTID}:role/password-caddy/lambda/${ENV}/cognito"
      CodeUri: src/controllers/login/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/login
            Method: GET
            ApiId: !Ref PasswordCaddyApi

Outputs:
  # Api
  PasswordCaddyApi:
    Description: "HTTP API Gateway URL for Password Caddy Api"
    Value: !Sub "https://${PasswordCaddyApi}.execute-api.${AWS::Region}.amazonaws.com/"
  
  # Endpoints
  LoginEndpoint:
    Description: "Endpoint for Login Lambda"
    Value: !Sub "https://${PasswordCaddyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/login"
  CreateUserEndpoint:
    Description: "Endpoint for Login Lambda"
    Value: !Sub "https://${PasswordCaddyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/user"
